swagger: '2.0'

info:
  title: mint-storage API
  version: '0.1'
  description: mint is STUPS' secret rotator and distributor.

externalDocs:
  description: STUPS documentation
  url: http://docs.stups.io

basePath: /
produces:
- application/json
consumes:
- application/json

security:
  - oauth2: [uid]

paths:

  '/':
    get:
      summary: Application root
      operationId: org.zalando.stups.friboo.system.http/redirect-to-swagger-ui
      responses:
        default:
          description: "Redirects to /ui/"

  '/apps':
    get:
      summary: list managed applications.
      description: |
        Provides a list of all applications, that are managed by mint. Optionally filter them via query parameters.
      tags:
        - Application
      operationId: org.zalando.stups.mint.storage.api/read-applications
      parameters:
        - name: resource_type_id
          in: query
          type: string
          description: ID of a resource type. Filters output to all applications, that use this resource type.
          required: false
          pattern: "^[a-z][a-z0-9-_]*(?:\\.[a-z0-9-_]*)?[a-z0-9]$"
        - name: scope_id
          in: query
          type: string
          description: |
            Id of a scope. Filters output to all applications, that use this scope.
            Make sure to also add the resource_type_id, because a sole scope_id might be ambiguous.
          required: false
          pattern: "^[a-z][a-z0-9-_]*[a-z0-9]$"
      responses:
        200:
          description: list of managed applications
          schema:
            description: all applications
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  description: Unique identifier
                  example: pierone
                last_password_rotation:
                  type: string
                  format: date-time
                  description: Last time, the password has been changed
                  example: "2015-06-14T15:30:00.000Z"
                last_client_rotation:
                  type: string
                  format: date-time
                  description: Last time, the client credentials have been changed
                  example: "2015-06-14T15:30:00.000Z"
                last_modified:
                  type: string
                  format: date-time
                  description: Last time, the configuration has been udated
                  example: "2015-06-14T15:30:00.000+01:00"
                last_synced:
                  type: string
                  format: date-time
                  description: Last time, the configuration has been synced to the service user API
                  example: "2015-06-14T15:30:00.000Z"
                has_problems:
                  type: boolean
                  description: Indicates, if an error occurred during the last sync
                  example: false
                message:
                  type: string
                  description: Error message from mint-worker
                  example: Access to bucket xyz denied
                s3_errors:
                  type: integer
                  description: How many times mint tried to put credentials in a bucket and failed
                  example: 2
              required:
                - id
                - has_problems
                - last_modified
                - s3_errors
        default:
          $ref: '#/responses/Error'

  '/apps/{application_id}':
    get:
      summary: read application
      description: |
        Returns state and configuration information about an application.
      tags:
        - Application
      operationId: org.zalando.stups.mint.storage.api/read-application
      parameters:
        - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: application information
          schema:
            type: object
            properties:
              id:
                type: string
                description: Unique identifier
                example: yourturn
              username:
                type: string
                description: Name of the service (robot) user
                example: yourturn
              client_id:
                type: string
                description: ID of the current OAuth 2.0 client configuration
                example: yourturn-12345
              last_password_rotation:
                type: string
                format: date-time
                description: Last time, the password has been changed
                example: "2015-06-14T15:30:00.000Z"
              last_client_rotation:
                type: string
                format: date-time
                description: Last time, the client credentials have been changed
                example: "2015-06-14T15:30:00.000Z"
              last_modified:
                type: string
                format: date-time
                description: Last time, the configuration has been udated
                example: "2015-06-14T15:30:00.000Z"
              last_synced:
                type: string
                format: date-time
                description: Last time, the configuration has been synced to the service user API
                example: "2015-06-14T15:30:00.000+02:00"
              has_problems:
                type: boolean
                description: Indicates, if an error occurred during the last sync
                example: false
              message:
                type: string
                description: Error message from mint-worker
                example: Access to bucket xyz denied
              s3_errors:
                type: integer
                description: How many times mint tried to put credentials in a bucket and failed
                example: 2
              redirect_url:
                type: string
                description: |
                  Which redirect URL is considered valid during the OAuth 2.0 implicit flow. Invalid redirect URLS are
                  not permitted
                example: https://yourturn.stups.example.org
              redirect_urls:
                type: array
                description: |
                  Which redirect URLs are considered valid during the OAuth 2.0 implicit flow. Invalid redirect URLs are
                  not permitted
                items:
                  type: string
                  example: https://yourturn.stups.example.org
              is_client_confidential:
                type: boolean
                description: |
                  Confidential clients are capable of keeping their credentials secret, e.g. application that are
                  running on a secured server. Non-confidential clients are incapable of keeping their credentials
                  secret, e.g. native desktop, mobile or browser apps. A public (non-confidential) client does not use
                  a password to authenticate its requests.
                example: true
              s3_buckets:
                type: array
                description: |
                  Unique bucket name, where the currently active credentials should be stored. Mint worker needs write
                  access to this bucket and the application itself need read access.
                items:
                  type: string
                  example: example-org-stups-mint
              scopes:
                type: array
                description: |
                  List of scopes, that this service user should be able to use
                items:
                  type: object
                  properties:
                    resource_type_id:
                      type: string
                      example: sales-order
                    scope_id:
                      type: string
                      example: read
            required:
              - id
              - username
              - last_modified
              - has_problems
              - is_client_confidential
              - s3_buckets
        default:
          $ref: '#/responses/Error'

    put:
      summary: create or update configuration
      description: |
        Creates or updates the application's configuration. If no s3 buckets are listed, the configuration will be
        deleted.
      tags:
        - Application
      operationId: org.zalando.stups.mint.storage.api/create-or-update-application
      parameters:
        - $ref: '#/parameters/ApplicationID'
        - name: application
          in: body
          schema:
            $ref: '#/definitions/ConfigurationUpdate'
      responses:
        200:
          description: configuration stored
        default:
          $ref: '#/responses/Error'

    patch:
      summary: update configuration status
      description: |
        Updates the application's configuration status.
      tags:
        - Status
      operationId: org.zalando.stups.mint.storage.api/update-application-status
      parameters:
        - $ref: '#/parameters/ApplicationID'
        - name: status
          in: body
          schema:
            $ref: '#/definitions/StatusUpdate'
      responses:
        200:
          description: configuration status updated
        default:
          $ref: '#/responses/Error'
      security:
        - oauth2:
          - uid
          - application.write_all_sensitive

    delete:
      summary: delete application configuration
      description: |
        Deletes an application configuration.
        Has the same effect than passing an empty s3 bucket list to the PUT request.
      tags:
        - Application
      operationId: org.zalando.stups.mint.storage.api/delete-application
      parameters:
        - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: configuration deleted
        default:
          $ref: '#/responses/Error'

  '/apps/{application_id}/renewal':
    post:
      summary: issue a renewal of the application's credentials as well as a sync of the service users.
      description: |
        Renews both client and user credentials of the application and resyncs service users.
      tags:
        - Application
      operationId: org.zalando.stups.mint.storage.api/renew-credentials!
      parameters:
        - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: renewal issued
        default:
          $ref: '#/responses/Error'

parameters:
  ApplicationID:
    name: application_id
    in: path
    type: string
    description: ID of the application. Must exist in Kio.
    required: true

responses:
  Error:
    description: An error occured.
    schema:
      $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Internal Server Error

  ConfigurationUpdate:
    type: object
    properties:
      redirect_url:
        type: string
        description: |
          Which redirect URL is considered valid during the OAuth 2.0 implicit flow. Invalid redirect URLs are
          not permitted
        example: https://yourturn.stups.example.org
        pattern: "^(https:\\/\\/.*|http:\\/\\/localhost(\\/.*)?)$"
      redirect_urls:
        type: array
        description: |
          Which redirect URLs are considered valid during the OAuth 2.0 implicit flow. Invalid redirect URLs are
          not permitted
        items:
          type: string
          example: https://yourturn.stups.example.org
          pattern: "^(https:\\/\\/.*|http:\\/\\/localhost(\\/.*)?)$"
      is_client_confidential:
        type: boolean
        description: |
          Confidential clients are capable of keeping their credentials secret, e.g. application that are
          running on a secured server. Non-confidential clients are incapable of keeping their credentials
          secret, e.g. native desktop, mobile or browser apps. A public (non-confidential) client does not use
          a password to authenticate its requests.
        example: true
      s3_buckets:
        type: array
        description: |
          Unique bucket name, where the currently active credentials should be stored. Mint worker needs write
          access to this bucket and the application itself needs read access.
        items:
          type: string
          example: example-org-stups-mint
          pattern: "^(gs://)?[a-z0-9][a-z0-9-.]{1,61}[a-z0-9]$"
      scopes:
        type: array
        description: |
          List of scopes, that this service user should be able to use. All scopes MUST exist in essentials.
        items:
          type: object
          properties:
            resource_type_id:
              type: string
              example: sales-order
            scope_id:
              type: string
              example: read
    required:
      - is_client_confidential

  StatusUpdate:
    type: object
    properties:
      client_id:
        type: string
        description: |
          Unique identifier of the OAuth client for this application. Generated by the service user API
      last_password_rotation:
        type: string
        format: date-time
        description: Last time, the password has been changed
        example: "2015-06-14T15:30:00.000Z"
      last_client_rotation:
        type: string
        format: date-time
        description: Last time, the client credentials have been changed
        example: "2015-06-14T15:30:00.000+01:00"
      last_synced:
        type: string
        format: date-time
        description: Last time, the configuration has been synced to the service user API
        example: "2015-06-14T15:30:00.000+02:00"
      has_problems:
        type: boolean
        description: Indicates, if an error occurred during the last sync
        example: false
      message:
        type: string
        description: Error message from mint-worker
        example: Access to bucket xyz denied
      s3_errors:
        type: integer
        description: How many times mint tried to put credentials in a bucket and failed
        example: 2

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
      application.write_all_sensitive: Write sensitive information of an application, e.g. credentials
